### ISSUE TITLE
Page needs to be reloaded on first view

### ISSUE THREAD

**Issue by UnsolvedCypher** [cubing/wca-inspection#7]
When cubing.net/inspection is first loaded, it says "FETCHING LATEST VERSION... PAGE WILL RELOAD IN A MOMENT" but the page never reloads and it is stuck on this message until the page is manually reloaded. To reproduce this issue, load it on a browser that has never loaded the page before or load it in incognito mode.

**Comment by lgarron** [comment]
Yeah, I don't know what's causing the reload to fail. :-(

I've just gone ahead ad removed the behaviour until I figure out something better.
Some day, the solution will probably just be service workers.

**Comment by UnsolvedCypher** [comment]
That was an amazingly fast response and solution. Looks like I need to update the judging cheat sheets I printed out now :)
